version: '3'

services:
  postgres:
    container_name: 'budget-tracker'
    restart: unless-stopped
    image: 'postgres:13'
    ports:
      - '15432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_PASSWORD: postgres 

  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    depends_on:
      - postgres

volumes:
  pgdata: {}